# -*- coding: utf-8 -*-
"""Project DA Customer Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161WsMfoeklcTz46jEoeIvyn-P30Ml0V0

# INPUT DATA
"""

# Mount drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/MyDrive/online_retail.csv"
df = pd.read_csv(path)
df.head()

"""# DATA UNDERSTANDING


"""

# Struktur data
df.info()

# Missing Value
df.isnull().sum()

"""initial data inspection shows missing data in "Description" and "CustomerID"
"""

# Summary
df.describe()

"""The dataset was initially inspected to understand its structure and data quality.
Several issues were identified during this phase:

- Missing values in the `CustomerID` column
- Non-positive values in `Quantity` and `UnitPrice`
- Inconsistent product descriptions

These issues will be addressed during the data cleaning stage based on the analytical objective of customer-level revenue and retention analysis.

# DATA CLEANING

## Valid Transaction Filtering (dropping non-positive value in `Quantity` and `UnitPrice`)
"""

# Check how many rows have non-positive Quantity or UnitPrice
invalid_qty = (df['Quantity'] <= 0).sum()
invalid_price = (df['UnitPrice'] <= 0).sum()

invalid_qty, invalid_price

# Keep only valid transactions
df_clean = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)].copy()

# Verify no non-positive values remain
(df_clean['Quantity'] <= 0).sum(), (df_clean['UnitPrice'] <= 0).sum()

"""## Dropping Missing `CustomerID`"""

# Check missing CustomerID
missing_cust = df_clean['CustomerID'].isna().sum()
missing_cust

# Remove rows with missing CustomerID
df_clean = df_clean.dropna(subset=['CustomerID']).copy()

# Verify no missing CustomerID remains
df_clean['CustomerID'].isna().sum()

"""## Date Formatting in `InvoiceDate`"""

# Convert to datetime first (kalau belum)
df_clean['InvoiceDate'] = pd.to_datetime(
    df_clean['InvoiceDate'],
    format='%m/%d/%Y %H:%M'
)

# Keep date only (remove time)
df_clean['InvoiceDate'] = df_clean['InvoiceDate'].dt.date

df_clean.info()
df_clean['InvoiceDate'].head()

"""# DATA UNDERSTANDING (CLEANED DATA)"""

# Data Structured
df_clean.info()

# Missing Value
df_clean.isnull().sum()

# Summary
df_clean.describe()

"""After the cleaning process, the data was **reduced to 397,884 data points from 541,909 data points.**

# ADDITIONAL FEATURES

## Adding `TotalAmount` Column
Created by multiplying `Quantity` and `UnitPrice`
to represent the actual monetary value of each transaction.
"""

# Create TotalAmount column
df_clean['TotalAmount'] = df_clean['Quantity'] * df_clean['UnitPrice']

df_clean[['Quantity', 'UnitPrice', 'TotalAmount']].head()

"""## Adding Reference Date

The reference date was defined as one day after the latest transaction date
to simulate the point in time immediately following the observed data period
"""

# Check the latest transaction date
df_clean['InvoiceDate'].max()

# Define reference date
reference_date = df_clean['InvoiceDate'].max() + pd.Timedelta(days=1)

print(f"Reference Date for RFM analysis: {reference_date}")

"""## Top Products"""

df_clean.groupby('Description')['TotalAmount'].sum().sort_values(ascending=False).head(5)

"""## Top Country"""

df_clean.groupby('Country')['TotalAmount'].sum().sort_values(ascending=False).head(5)

"""# RFM MEASURING (FOR EACH CUSTOMER)"""

rfm = df_clean.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda x: (reference_date - x.max()).days),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('TotalAmount', 'sum')
).reset_index()

rfm.head()

rfm['CustomerID'] = rfm['CustomerID'].astype(str)

# RFM Sanity Check
rfm.describe()

"""# CUSTOMER REVENUE ANALYSIS

## Total Revenue Overview
"""

total_revenue = rfm['Monetary'].sum()
total_customers = rfm.shape[0]
avg_revenue_per_customer = total_revenue / total_customers

print(f"Total revenue: {total_revenue}")
print(f"Total customers: {total_customers}")
print(f"Average revenue per customer: {avg_revenue_per_customer}")

"""The dataset contains 4338 customers with a total revenue of
8,911,407.904 USD. On average, each customer contributes about 2,054.27 USD
to total revenue.

## Revenue Distribution
"""

# Histogram
import matplotlib.pyplot as plt

plt.hist(rfm['Monetary'], bins=50)
plt.xlabel('Customer Revenue')
plt.ylabel('Number of Customers')
plt.title('Distribution of Customer Revenue')
plt.show()

"""### Pareto Analysis"""

import numpy as np

rfm_sorted = rfm.sort_values(by='Monetary', ascending=False)

rfm_sorted['CumulativeRevenue'] = rfm_sorted['Monetary'].cumsum()
rfm_sorted['CumulativeRevenuePct'] = (
    rfm_sorted['CumulativeRevenue'] / total_revenue
)

rfm_sorted['CustomerPct'] = (
    (np.arange(1, total_customers + 1)) / total_customers
)

rfm_sorted.head()

"""### Pareto Chart"""

plt.plot(rfm_sorted['CustomerPct'], rfm_sorted['CumulativeRevenuePct'])
plt.axhline(0.8, linestyle='--')
plt.axvline(0.2, linestyle='--')
plt.xlabel('Cumulative % of Customers')
plt.ylabel('Cumulative % of Revenue')
plt.title('Pareto Analysis: Customer Revenue Contribution')
plt.show()

rfm_sorted[rfm_sorted['CumulativeRevenuePct'] <= 0.8].shape[0] / total_customers

"""Approximately **26%** of customers contribute around **80%** of total revenue"""

import matplotlib.pyplot as plt

plt.hist(rfm['Recency'], bins=50)
plt.xlabel('Recency (days)')
plt.ylabel('Number of Customers')
plt.title('Distribution of Customer Recency')
plt.show()

"""# RFM SCORING"""

# RFM Scoring using quantiles (robust to skewness)

rfm['R_Score'] = pd.qcut(
    rfm['Recency'], 5, duplicates='drop'
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'], 5, duplicates='drop'
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'], 5, duplicates='drop'
)


rfm[['R_Score','F_Score','M_Score']].head()

rfm['R_Score'] = rfm['R_Score'].cat.codes
rfm['F_Score'] = rfm['F_Score'].cat.codes
rfm['M_Score'] = rfm['M_Score'].cat.codes

rfm['R_Score'] = rfm['R_Score'].max() - rfm['R_Score']

"""## RFM Preview"""

rfm[['R_Score','F_Score','M_Score']].describe()
rfm[['R_Score','F_Score','M_Score']].head()

rfm[['R_Score','F_Score','M_Score']].describe()

"""## Profiling Based on RFM Score"""

def assign_customer_profile(row):
    if row['R_Score'] >= 3 and row['F_Score'] >= 3 and row['M_Score'] >= 3:
        return 'Loyal'
    elif row['R_Score'] >= 3 and row['F_Score'] >= 2 and row['M_Score'] >= 2:
        return 'Potential Loyalist'
    elif row['R_Score'] <= 1 and row['M_Score'] >= 3:
        return 'At Risk High Value'
    elif row['R_Score'] >= 3 and row['F_Score'] <= 1:
        return 'New Customers'
    else:
        return 'Lost / Low Engagement'

rfm['CustomerProfile'] = rfm.apply(assign_customer_profile, axis=1)

"""## Customer Distribution"""

rfm['CustomerProfile'].value_counts()

"""## Revenue Distribution"""

rfm.groupby('CustomerProfile')['Monetary'].sum().sort_values(ascending=False)

"""## Recency Distribution"""

rfm.groupby('CustomerProfile')['Recency'].mean().sort_values(ascending=False)

rfm['CustomerProfile'] \
    .value_counts() \
    .sort_index() \
    .plot(kind='bar')

plt.title('Customer Segment Distribution')
plt.xlabel('Customer Segment')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.show()

rfm.groupby('CustomerProfile')['Monetary'].sum().plot(kind='bar')
plt.title('Revenue Contribution per Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.show()

rfm.groupby('CustomerProfile')['Recency'].mean().plot(kind='bar')
plt.title('Revenue Contribution per Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.show()

plt.scatter(
    rfm['Recency'],
    rfm['Frequency'],
    s=rfm['Monetary'] / rfm['Monetary'].max() * 300,
    alpha=0.5
)
plt.xlabel('Recency (days)')
plt.ylabel('Frequency')
plt.title('Customer RFM Distribution')
plt.show()

"""# DOWNLOAD ANALYSIS RESULT (CSV)"""

# Cleaned the Customer ID
df_clean['CustomerID'] = (
    df_clean['CustomerID']
    .astype(str)
    .str.replace('.0', '', regex=False)
)

rfm['CustomerID'] = (
    rfm['CustomerID']
    .astype(str)
    .str.replace('.0', '', regex=False)
)

# Customer-level table
rfm_dashboard = rfm[['CustomerID','CustomerProfile','Recency','Frequency','Monetary']].copy()
rfm_dashboard.to_csv('rfm_customer_dashboard.csv', index=False)

# Transaction-level table with profile
df_dashboard = df_clean.merge(
    rfm[['CustomerID','CustomerProfile']],
    on='CustomerID',
    how='left'
)
df_dashboard.to_csv('transactions_dashboard.csv', index=False)